default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: POST

default_login:
    path: /login 
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST

default_logout:
    path: /logout 
    defaults: { _controller: "AppBundle:Default:logout" }
    methods: POST    

default_returnidentity:
    path: /returnidentity 
    defaults: { _controller: "AppBundle:Default:returnidentity" }
    methods: POST    