documento_new:
    path: /new
    defaults: { _controller: "AppBundle:Documento:new" }
    methods: POST

documento_listall:
    path: /listall
    defaults: { _controller: "AppBundle:Documento:listall" }
    methods: POST    

documento_returnone:
    path: /returnone
    defaults: { _controller: "AppBundle:Documento:returnone" }
    methods: POST  

documento_delete:
    path: /delete
    defaults: { _controller: "AppBundle:Documento:delete" }
    methods: POST        

documento_listnew:
    path: /listnew
    defaults: { _controller: "AppBundle:Documento:listnew" }
    methods: POST 

documento_listprueba:
    path: /listprueba
    defaults: { _controller: "AppBundle:Documento:listprueba" }
    methods: POST             

documento_cambiarestado:
    path: /cambiarestado
    defaults: { _controller: "AppBundle:Documento:cambiarestado" }
    methods: POST              