mensaje_new:
    path: /new
    defaults: { _controller: "AppBundle:Mensaje:new" }
    methods: POST

mensaje_listall:
    path: /listall
    defaults: { _controller: "AppBundle:Mensaje:listall" }
    methods: POST    

mensaje_user:
    path: /messageuser
    defaults: { _controller: "AppBundle:Mensaje:messageuser" }
    methods: POST        