modelo_new:
    path: /new
    defaults: { _controller: "AppBundle:Modelo:new" }
    methods: POST

modelo_listall:
    path: /listall
    defaults: { _controller: "AppBundle:Modelo:listall" }
    methods: POST   

modelo_returnone:
    path: /returnone
    defaults: { _controller: "AppBundle:Modelo:returnone" }
    methods: POST       