sesion_new:
    path: /new
    defaults: { _controller: "AppBundle:Sesion:new" }
    methods: POST

sesion_allsessions:
    path: /allsessions
    defaults: { _controller: "AppBundle:Sesion:allsessions" }
    methods: POST    
