<?php

namespace ModelBundle\Repository;

/**
 * DescargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescargaRepository extends \Doctrine\ORM\EntityRepository
{
}
